version: "3.5"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/app
    env_file:
      - local.env
    depends_on:
            - postgres

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file: local.env
