version: "3.5"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/app
    env_file:
      - local.env
    depends_on:
      - postgres
    environment:
      WAIT_HOSTS: postgres:5432

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ".pg-persistent-data:/var/lib/postgresql/data"
    env_file: local.env
